### ISSUE TITLE
Strange hover effects

### ISSUE THREAD

**Issue by shibaev** [opa-kostik/pathfinder#2]
In the latest version of Chrome on Windows 10:
1. Cells look "corrupted" after you moved mouse over cells (look at right-bottom angle in the screenshot)
2. Try to set start/end in the same cell multiple times (make few clicks). Cell will be rendered partially.

Screenshot: https://dl.dropboxusercontent.com/u/9287830/hover%20effects.png

I think you need to use more conservative rules for "td:hover"

**Comment by opa-kostik** [comment]
Reopened the issue. I was able to reproduce a bug. It happens when you drag and drop a table cell
